### ISSUE TITLE
Add Legacy/CloudEvent Event Mapping

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-conformance#2]
We should document the exact mapping for Legacy to CloudEvent payloads.

I suggest we use this repo to store mappings and add tooling to ensure the mapping in a specific framework is correct.

The first step would be to describe the mapping (ideally language-agnostically).

CC: @jskeet
See: go/bridging-event-types-in-the-functions-framework

**Comment by grant** [comment]
For example, these tests:

https://github.com/GoogleCloudPlatform/functions-framework-dotnet/tree/master/src/Google.Cloud.Functions.Framework.Tests/GcfEvents

**Comment by jskeet** [comment]
I'm happy to write up a doc when everything's finalized - we're still nailing down the subject/source/type parts.

**Comment by grant** [comment]
@jskeet Do you think things are more finalized now? I think we can at least move some of the decisions as documentation to the public conformance testing tool.

**Comment by jskeet** [comment]
@grant: I think we're in good shape for Storage, CAL, PubSub and Scheduler. I can start writing those up next week.
