### ISSUE TITLE
Consider testing non-data aspects

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework-conformance#63]
For Firebase events, we have quite a lot of transformation work for CloudEvent context attributes. At the moment, this can't be tested by the conformance tests, which is a bit of a hole.

Doing this would require changing our input/output format fairly significantly, I suspect.

**Comment by jskeet** [comment]
My mistake - it looks like the files as the structural representation, so do include the attributes.
Great - that should enable a bunch more tests.

**Comment by mtraver** [comment]
I will look over the set of attributes we validate though and make sure it's complete.
