### ISSUE TITLE
PHP: Conformance tests suddenly failing

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-conformance#77]
Without updating our conformance test action version, and without changing any code in the repo, the conformance tests in [functions-framework-php](https://github.com/GoogleCloudPlatform/functions-framework-php) have [begun to fail](https://github.com/GoogleCloudPlatform/functions-framework-php/actions/workflows/conformance.yml). The errors boil down to two types of errors, one for firebase and one for pubsub:

```
- firebase-db7:
    - unexpected "source" field in "firebase-db7": got //firebasedatabase.googleapis.com/projects/_/instances/my-project-id, want //firebasedatabase.googleapis.com/projects/_/locations/us-central1/instances/my-project-id

- pubsub_text:
    - unexpected "data" field in "pubsub_text": got map[message:map[@type:type.googleapis.com/google.pubsub.v1.PubsubMessage attributes:map[attr1:attr1-value] data:dGVzdCBtZXNzYWdlIDM=]], want map[message:map[@type:type.googleapis.com/google.pubsub.v1.PubsubMessage attributes:map[attr1:attr1-value] data:dGVzdCBtZXNzYWdlIDM= messageId:aaaaaa-1111-bbbb-2222-cccccccccccc publishTime:2020-09-29T11:32:00.000Z]]
```

As we haven't changed the code, and given the strange difference in at least the firebase errors, I believe at least that one to be an error in this library and not in our code. The pubsub errors may be a result of new tests having been added? Even this is strange though, as we have been pinned to `0.3.9` the whole time.

**Comment by bshaffer** [comment]
1. For the firebase errors, we were matching on the following regex:

```
#^(projects/_/instances/[^/]+)/(refs/.+)$#
```
We can update it to the following:
```
#^(projects/_/locations/[^/]+/instances/[^/]+)/(refs/.+)$#
```

Is that correct, or should it potentially match both?

2. For the pubsub error, We are decoding the JSON body and populating `data` with those contents. Should we be manually populating the (currently missing) `messageId` and `publishTime` fields with the values from some other fields?

**Comment by grant** [comment]
This looks related to changes with https://github.com/GoogleCloudPlatform/functions-framework-conformance/pull/76

@jskeet @matthewrobertson, do you know this change / issue?

**Comment by jskeet** [comment]
If the PHP repo is always pulling "HEAD", then yes, that could easily cause it. I'd expected repos to either use submodules or similar to pin to a specific version, so that the conformance repo itself could be updated and then implementations move their pin over time.

For the Firebase repo, I'm not sure what you're asking, @bshaffer - if this is for legacy to CloudEvent conversion, you shouldn't expect the location to be in the legacy event; you populate it in the source for the CloudEvent. See the changes in the mapping.md file in #76 for details.

And for PubSub, yes, messageId and publishId should be populated - again, mapping.md gives the details.

**Comment by matthewrobertson** [comment]
Digging into [one of the failing runs](https://github.com/GoogleCloudPlatform/functions-framework-php/runs/3030270323?check_suite_focus=true), it looks like the action version is not being respected. Maybe we haven't configured things correctly?

```
Run GoogleCloudPlatform/functions-framework-conformance/action@v0.3.9
go: found github.com/GoogleCloudPlatform/functions-framework-conformance/client in github.com/GoogleCloudPlatform/functions-framework-conformance v0.3.12
```

**Comment by matthewrobertson** [comment]
The [Github action docs suggest](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management) that we should have bumped the major version when we introduced the change for the payload formats, as this was a breaking change.

> Introduce a new major version tag (v2) for changes that will break existing workflows. For example, changing an action's inputs would be a breaking change.

Maybe this is implying that they do not respect minor or patch versions.

**Comment by bshaffer** [comment]
@jskeet it wasn't supposed to be pulling head but as @matthewrobertson pointed out, apparently it was anyway. 

I'll take a look at the mapping.md to see if i can find out what changed.

**Comment by bshaffer** [comment]
It sure would be weird of Github actions didn't allow pinning to minor versions...

**Comment by grant** [comment]
I believe this issue has also appeared with Java, which had it's first commit (that just bumps deps) since July 6th.

https://github.com/GoogleCloudPlatform/functions-framework-java/runs/3386440189

**Comment by bshaffer** [comment]
This has been addressed in https://github.com/GoogleCloudPlatform/functions-framework-php/pull/103
