### ISSUE TITLE
Action always installs the latest version of the conformance testing client

### ISSUE THREAD

**Issue by di** [GoogleCloudPlatform/functions-framework-conformance#81]
Conformance tests started failing for `functions-framework-python` sometime after Aug 10 without significant changes to that repository: https://github.com/GoogleCloudPlatform/functions-framework-python/issues/148

Is there anything that changed here which could be the root cause?

**Comment by jskeet** [comment]
Are you able to rerun the tests at arbitrary commits of this repo, to find out what the problem is? I'm afraid I can't easily tell from the error message what's going wrong.

**Comment by anniefu** [comment]
It's because Python FF is failing v1.0.0 of the FF conformance tests, which includes an updated standard for firebase and pubsub event conversion.

GitHub Actions does not respect the version pinned in the config yaml for the [Python repo](https://github.com/GoogleCloudPlatform/functions-framework-python/blob/master/.github/workflows/conformance.yml), which is a problem.

cc @matthewrobertson

**Comment by di** [comment]
> GitHub Actions does not respect the version pinned in the config yaml for the Python repo, which is a problem.

I don't think this is right, the [first failed run](https://github.com/GoogleCloudPlatform/functions-framework-python/runs/3414035673) claims that it is downloading the correct pinned version of the action:

> ```Download action repository 'GoogleCloudPlatform/functions-framework-conformance@v0.3.12' (SHA:e04a130a10f5548d34d15c00d8d329e7e8c593ad)```


The issue seems to be that this action installs the latest version of the client regardless of what version of the action is being used:

https://github.com/GoogleCloudPlatform/functions-framework-conformance/blob/05e150eafaa097535a56816e59d112a56b0d169c/action/src/index.ts#L47-L49

Can we:

- [ ] fix this issue for future tags
- [ ] add a new < 1.0.0 tag with this fix cherrypicked in

**Comment by anniefu** [comment]
Ah, that makes more sense. I can take a pass at fixing this today.
