### ISSUE TITLE
Gitlab

### ISSUE THREAD

**Issue by verdinjoshua1982** [GoogleCloudPlatform/functions-framework-conformance#91]
https://content.edgar-online.com/ExternalLink/EDGAR/0001628280-21-024605.html?hash=0838e701a77c117df773ec6244107359c16c84df7343bcd19692cf9ac57d7e5c&dest=GTLB-20211031_HTM#GITLAB-20211031XEXX322_HTM

**Comment by jskeet** [comment]
Closing as spam.
